final List<Map<String, dynamic>> CATEGORIES = [
  {'name': 'Food & Restaurants', 'icon': 58732, 'enabled': true},
  {'name': 'Cafe & Bars', 'icon': 58688, 'enabled': true},
  {'name': 'Hobbies', 'icon': 58378, 'enabled': true},
  {'name': 'Clothes', 'icon': 59692, 'enabled': true},
  {'name': 'Health & Hospital', 'icon': 58704, 'enabled': true},
  {'name': 'Banks & Fees', 'icon': 59471, 'enabled': true},
  {'name': 'Holidays & Travel', 'icon': 60222, 'enabled': true},
  {'name': 'Transportation', 'icon': 58673, 'enabled': true},
  {'name': 'Gifts', 'icon': 59638, 'enabled': true},
  {'name': 'Subscriptions & Recurring', 'icon': 60221, 'enabled': true},
  {'name': 'Entertainment', 'icon': 58701, 'enabled': true},
  {'name': 'Business', 'icon': 59641, 'enabled': true},
  {'name': 'Electronics', 'icon': 58167, 'enabled': true},
  {'name': 'Physical Activities', 'icon': 60227, 'enabled': true},
  {'name': 'Maintenance', 'icon': 57923, 'enabled': true},
  {'name': 'Games & Apps', 'icon': 58168, 'enabled': true},
  {'name': 'Housing', 'icon': 59530, 'enabled': true},
  {'name': 'Groceries', 'icon': 60231, 'enabled': true},
  {'name': 'TV & Streaming', 'icon': 58937, 'enabled': true},
  {'name': 'Shopping/General', 'icon': 58695, 'enabled': true},
  {'name': 'Pets', 'icon': 59677, 'enabled': true},
  {'name': 'School', 'icon': 59404, 'enabled': true},
  {'name': 'Communications', 'icon': 58155, 'enabled': true},
];